name: mes_lite
description: ""
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state and bisness logic
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  provider: ^6.1.5+1

  # local storage
  shared_preferences: ^2.5.3

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
